@SoftwareCenter.Api_HostAddress = http://localhost:1337

POST {{SoftwareCenter.Api_HostAddress}}/vendors
Authorization: Bearer
Accept: application/json
Content-type: application/json

{
"name": "Docker",
"url": "https://docker.com",
"pointOfContact": {
    "name": "Silvio",
    "email": "silvio@jbrain.com",
    "phone": "800 Write-Code"
}
}


### 

GET {{SoftwareCenter.Api_HostAddress}}/vendors/e506c810-taco-salad


### 
GET {{SoftwareCenter.Api_HostAddress}}/vendors/
Authorization: Bearer


###

GET {{SoftwareCenter.Api_HostAddress}}/info


###

POST {{SoftwareCenter.Api_HostAddress}}/vendors/0a09877f-1bca-4c6e-aef8-b83cc55728c4/items 
Accept: application/json
Content-Type: application/json

{
    "name": "Word",
    "description": "Do words and stuff",
    "version": "2025"
}

###

PUT {{SoftwareCenter.Api_HostAddress}}/vendors/0a09877f-1bca-4c6e-aef8-b83cc55728c4/point-of-contact
Authorization: Bearer 
Accept: application/json
Content-Type: application/json

{
  "name": "Robert",
  "phone": "1234567890",
  "email": "Rob@aol.com"
}