@SoftwareCenter.Api_HostAddress = http://localhost:1337

POST {{SoftwareCenter.Api_HostAddress}}/vendors
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImJvYkBhb2wuY29tIiwic3ViIjoiYm9iQGFvbC5jb20iLCJqdGkiOiJiNjU1YjYzNyIsInJvbGUiOlsiU29mdHdhcmVDZW50ZXIiLCJNYW5hZ2VyIl0sImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6MTMzNyIsIm5iZiI6MTc1Mzk5MzQ4NywiZXhwIjoxNzYxOTQyMjg3LCJpYXQiOjE3NTM5OTM0ODgsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.gEbCCxgfXSPDBrjlQWwIJKWcFhfsULNOSy_VkWnavW4
Accept: application/json
Content-type: application/json

{
"name": "Docker",
"url": "https://docker.com",
"pointOfContact": {
    "name": "Silvio",
    "email": "silvio@jbrain.com",
    "phone": "800 Write-Code"
}
}

PUT {{SoftwareCenter.Api_HostAddress}}/vendors/id/point-of-contact
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImJvYkBhb2wuY29tIiwic3ViIjoiYm9iQGFvbC5jb20iLCJqdGkiOiJiNjU1YjYzNyIsInJvbGUiOlsiU29mdHdhcmVDZW50ZXIiLCJNYW5hZ2VyIl0sImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6MTMzNyIsIm5iZiI6MTc1Mzk5MzQ4NywiZXhwIjoxNzYxOTQyMjg3LCJpYXQiOjE3NTM5OTM0ODgsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.gEbCCxgfXSPDBrjlQWwIJKWcFhfsULNOSy_VkWnavW4
Accept: application/json
Content-type: application/json

{
   "name": "NewSilvio",
   "email": "newsilvio@jbrain.com",
   "phone": "800 Write-Code-New"
}


### 

GET {{SoftwareCenter.Api_HostAddress}}/vendors/e506c810-taco-salad


### 
GET {{SoftwareCenter.Api_HostAddress}}/vendors/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImJvYkBhb2wuY29tIiwic3ViIjoiYm9iQGFvbC5jb20iLCJqdGkiOiJiNjU1YjYzNyIsInJvbGUiOlsiU29mdHdhcmVDZW50ZXIiLCJNYW5hZ2VyIl0sImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6MTMzNyIsIm5iZiI6MTc1Mzk5MzQ4NywiZXhwIjoxNzYxOTQyMjg3LCJpYXQiOjE3NTM5OTM0ODgsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.gEbCCxgfXSPDBrjlQWwIJKWcFhfsULNOSy_VkWnavW4


###

GET {{SoftwareCenter.Api_HostAddress}}/info


###

POST {{SoftwareCenter.Api_HostAddress}}/vendors/c53f4f43-71cd-45bb-9333-2c7cf9afbfaf/items 
Content-Type: application/json

{
    "name": "Word",
    "description": "Do words and stuff",
    "version": "2025"
}
