@SoftwareCenter.Api_HostAddress = http://localhost:1337

POST {{SoftwareCenter.Api_HostAddress}}/vendors
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Im1lZ0Bhb2wuY29tIiwic3ViIjoibWVnQGFvbC5jb20iLCJqdGkiOiI5MzBiNTE1MCIsInJvbGUiOlsiTWFuYWdlciIsIlNvZnR3YXJlQ2VudGVyIl0sImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6MTMzNyIsIm5iZiI6MTc1Mzk5Njk4OCwiZXhwIjoxNzYxOTQ1Nzg4LCJpYXQiOjE3NTM5OTY5ODksImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.PwUzT6YTgcFKiCwYsDi965MOt47oyP1u_2A8xWZdgM8
Accept: application/json
Content-type: application/json

{
"name": "Docker",
"url": "https://docker.com",
"pointOfContact": {
    "name": "Silvio",
    "email": "silvio@jbrain.com",
    "phone": "800 Write-Code"
}
}


### 

GET {{SoftwareCenter.Api_HostAddress}}/vendors/e506c810-taco-salad


### 
GET {{SoftwareCenter.Api_HostAddress}}/vendors/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImJvYkBhb2wuY29tIiwic3ViIjoiYm9iQGFvbC5jb20iLCJqdGkiOiJjNGI1MDFiYiIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6MTMzNyIsIm5iZiI6MTc1Mzk5MzI4NywiZXhwIjoxNzYxOTQyMDg3LCJpYXQiOjE3NTM5OTMyODgsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.jHhQgcrhi82u1IFh2TDpMbzgJzzqn3Wye13bNdnDUFM


###

GET {{SoftwareCenter.Api_HostAddress}}/info


###

POST {{SoftwareCenter.Api_HostAddress}}/vendors/c53f4f43-71cd-45bb-9333-2c7cf9afbfaf/items 
Content-Type: application/json

{
    "name": "Word",
    "description": "Do words and stuff",
    "version": "2025"
}
###


PUT {{SoftwareCenter.Api_HostAddress}}/vendors/{id}/point-of-contact
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Im1lZ0Bhb2wuY29tIiwic3ViIjoibWVnQGFvbC5jb20iLCJqdGkiOiI5MzBiNTE1MCIsInJvbGUiOlsiTWFuYWdlciIsIlNvZnR3YXJlQ2VudGVyIl0sImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6MTMzNyIsIm5iZiI6MTc1Mzk5Njk4OCwiZXhwIjoxNzYxOTQ1Nzg4LCJpYXQiOjE3NTM5OTY5ODksImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.PwUzT6YTgcFKiCwYsDi965MOt47oyP1u_2A8xWZdgM8
Content-Type: application/json

{
      "name": "new name",
      "phone": "new phone",
      "email": "new email"
}